# Generated by Django 5.0.7 on 2024-07-21 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_basket_product_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='created',
            field=models.BooleanField(default=True),
        ),
    ]
